apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: mahesh142/node-app:latest 
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGO_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer # Standard for EKS to get an External DNS/IP
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
